### ISSUE TITLE
pareto-anywhere version 1.4.7: dependency on non existing advlib 1.1.2

### ISSUE THREAD

**Issue by kaplanlior** [reelyactive/pareto-anywhere#4]
Hi,

Installation of pareto-anywhere failed since latest advlib on NPM is 1.1.1 (https://www.npmjs.com/package/advlib), while package.json looks for 1.1.2 due to  3bd06e230f61a48967942da66155408ec62a17ba

@jeffyactive Can you check ?

**Comment by jeffyactive** [comment]
Thanks for raising this issue @kaplanlior.  Indeed, advlib@1.1.2 was committed on GitHub but not published to npm, making the dependency fail.  This has been corrected with the publishing of advlib@1.1.2 on npm just now.  Sorry for the inconvenience!
